.PHONY: all clean clean-data clean-all init kernel kernel-config cjsh display cmd cmd-rs squishy dinky build-image image sd-card run run-shell-only run-graphical run-graphical-shell-only run-g run-gs run-g-dev run-gs-dev
ROOT      := $(CURDIR)
BUILD     := $(ROOT)/build
USERLAND  := $(ROOT)/userland
DISK      := $(ROOT)/disk
DOCKER_IMAGE := cjyx-static
# Target platform for the guest userland. Passed to docker build/create so the
# image and everything extracted from it is aarch64 (built via qemu-user/binfmt
# on the x86_64 host) — and set here rather than as a constant in the Dockerfile
# FROM lines, which docker lints against.
PLATFORM := linux/arm64
ZONULE_SRC  := $(USERLAND)/display/zonule
SQUISHY_SRC := $(USERLAND)/apps/squishy
DINKY_SRC   := $(USERLAND)/apps/dinky
CMDRS_SRC   := $(USERLAND)/cmd
WORKSPACE   := $(USERLAND)/Cargo.toml
# Our own kernel — one multiplatform arm64 Image (aarch64) that boots BOTH the
# QEMU `-M virt` dev VM and a real Raspberry Pi 4 (BCM2711). Built from
# kernel/src with virtio, vc4/v3d, bcm2711 mmc/genet/pcie, ext4, etc. all
# compiled in (no module loading infrastructure in this OS).
CROSS_COMPILE ?= aarch64-linux-gnu-
KERNEL_SRC := $(ROOT)/kernel/src
KERNEL := $(KERNEL_SRC)/arch/arm64/boot/Image
KCONFIG := $(KERNEL_SRC)/.config
KCONFIG_FRAGMENT := $(ROOT)/kernel/cjyx_rpi4.config
# Device tree for the real Pi 4 — copied onto the SD boot partition (the QEMU
# `-M virt` path ignores it and gets its DT from QEMU directly).
DTB := $(KERNEL_SRC)/arch/arm64/boot/dts/broadcom/bcm2711-rpi-4-b.dtb
IMG    := $(BUILD)/disk.img
# Persistent /home for the QEMU dev loop. disk.img (root) is regenerated by
# mkfs on every `make run`, so anything on it is wiped each build. data.img is a
# separate virtio disk (/dev/vdb) created ONCE and never rebuilt, so files in
# /home survive image rebuilds. On the real Pi there's no second disk — /home
# just lives on the SD root, which persists across reboots on its own.
DATA   := $(BUILD)/data.img
SDIMG  := $(BUILD)/sdcard.img
RPIBOOT := $(DISK)/rpi-boot
# 2048MB matches the Pi 4 2GB target. Mesa llvmpipe alone wants several
# hundred MB of working set, plus per-app overhead.
#
# We build arm64 on an x86_64 host, so this is TCG emulation — no -enable-kvm
# (host KVM can't accelerate a foreign guest arch).
QEMU_COMMON := qemu-system-aarch64 \
  -M virt \
  -cpu cortex-a72 \
  -kernel $(KERNEL) \
  -drive file=$(IMG),format=raw,if=virtio \
  -drive file=$(DATA),format=raw,if=virtio \
  -m 2048
QEMU_HEADLESS := $(QEMU_COMMON) -nographic
# virtio-gpu-pci gives wlroots a real DRM device (modesetting/GBM/atomic) under
# `-M virt`; virtio-keyboard/tablet give the compositor input devices. The Pi's
# own VideoCore is not emulated here — this path renders via llvmpipe.
QEMU_GRAPHICAL := $(QEMU_COMMON) -display gtk,gl=on -device virtio-gpu-gl-pci \
  -device virtio-keyboard-pci -device virtio-tablet-pci
# QEMU virt serial is ttyAMA0 (PL011), same as the Pi — so one cmdline works.
ROOT_CMDLINE := root=/dev/vda rootfstype=ext4 rw console=ttyAMA0

all: image

$(BUILD):
	mkdir -p $(BUILD)

# Persistent /home data disk. This is a real file target (not phony), so once
# it exists Make never rebuilds it — your /home survives every `make run`.
# Delete it with `make clean-data` to reset /home. (^metadata_csum for the same
# reason as the root image; see disk/Makefile.)
$(DATA): | $(BUILD)
	truncate -s 256M $(DATA)
	mkfs.ext4 -F -q -O ^metadata_csum $(DATA)

# Kernel is cross-compiled on the HOST (not emulated in docker) — kernel builds
# are far too large to run under qemu-user. Needs the aarch64-linux-gnu- GCC
# toolchain on PATH. Builds the arm64 Image plus the Pi 4 device tree.
#
# The .config is generated from the stock arm64 defconfig + our fragment. It's
# regenerated whenever the fragment changes (which resets any manual `menuconfig`
# tweaks — re-apply them to the fragment to keep them). Run `make kernel-config`
# to force a regen.
kernel: $(KERNEL)

kernel-config:
	rm -f $(KCONFIG)
	$(MAKE) $(KCONFIG)

$(KCONFIG): $(KCONFIG_FRAGMENT)
	$(MAKE) -C $(KERNEL_SRC) ARCH=arm64 CROSS_COMPILE=$(CROSS_COMPILE) defconfig
	cd $(KERNEL_SRC) && ARCH=arm64 ./scripts/kconfig/merge_config.sh -m .config $(KCONFIG_FRAGMENT)
	$(MAKE) -C $(KERNEL_SRC) ARCH=arm64 CROSS_COMPILE=$(CROSS_COMPILE) olddefconfig

$(KERNEL): $(KCONFIG)
	$(MAKE) -C $(KERNEL_SRC) ARCH=arm64 CROSS_COMPILE=$(CROSS_COMPILE) Image dtbs

init: $(BUILD)/init
$(BUILD)/init: $(DISK)/cinit.c | $(BUILD)
	$(MAKE) -C $(DISK) init
	cp $(DISK)/init $(BUILD)/init

cjsh: $(BUILD)/cjsh
display: $(BUILD)/display
squishy: $(BUILD)/squishy
dinky: $(BUILD)/dinky

build-image:
	docker build \
	  --platform $(PLATFORM) \
	  --build-arg BUILD_TARGET=static \
	  -t $(DOCKER_IMAGE) \
	  -f $(USERLAND)/Dockerfile \
	  $(USERLAND)

$(BUILD)/cjsh: build-image | $(BUILD)
	cid=$$(docker create --platform $(PLATFORM) $(DOCKER_IMAGE)); \
	  docker cp $$cid:/cjyx/cjsh/cjsh $(BUILD)/cjsh; \
	  docker rm $$cid >/dev/null

# The compositor (zonule) is a Rust/Smithay program — it builds in its own
# rust:1-bookworm toolchain image like squishy/dinky, NOT in the cjyx-static C
# image. It's still installed into the rootfs as `bin/display` (cinit launches
# `/bin/display`), so only this rule changes, not the disk staging.
# Set ZONULE_DEV=1 to build the fast no-LTO iteration profile (see zonule's
# Cargo.toml). `make run-g-dev` is a shortcut. NOTE: the built binary lives at
# one path ($(BUILD)/display) regardless of profile, so the mode "sticks" to
# whatever last built it — touch a src file (you will anyway) or `rm
# $(BUILD)/display` to force a switch between dev and release.
$(BUILD)/display: $(ZONULE_SRC)/build.py $(ZONULE_SRC)/Dockerfile.build $(ZONULE_SRC)/Cargo.toml $(ZONULE_SRC)/Cargo.lock $(shell find $(ZONULE_SRC)/src -name '*.rs') | $(BUILD)
	python3 $(ZONULE_SRC)/build.py $(if $(ZONULE_DEV),--dev,) $(BUILD)/display

# asemics is a Rust workspace member (see userland/Cargo.toml), so it's built
# by the cmd-rs workspace build and installed into the image by the disk
# Makefile's stage-cmd-rs — no dedicated target here.

# Squishy is Rust, so it builds in its own toolchain image (rust:1-bookworm)
# instead of the cjyx-static C image. The Python helper handles the docker
# build/run dance and the binary install.
$(BUILD)/squishy: $(SQUISHY_SRC)/build.py $(SQUISHY_SRC)/Dockerfile.build $(SQUISHY_SRC)/Cargo.toml $(SQUISHY_SRC)/Cargo.lock $(wildcard $(SQUISHY_SRC)/src/*.rs) $(wildcard $(SQUISHY_SRC)/assets/*) | $(BUILD)
	python3 $(SQUISHY_SRC)/build.py $(BUILD)/squishy

# Same Rust-in-docker pattern as squishy. Dinky's builder image is leaner
# (no xkbcommon-dev — ratatui + crossterm are pure Rust).
$(BUILD)/dinky: $(DINKY_SRC)/build.py $(DINKY_SRC)/Dockerfile.build $(DINKY_SRC)/Cargo.toml $(DINKY_SRC)/Cargo.lock $(wildcard $(DINKY_SRC)/src/*.rs) | $(BUILD)
	python3 $(DINKY_SRC)/build.py $(BUILD)/dinky

# palmer is a Rust workspace member, so it's built by the cmd-rs workspace build
# and installed by the disk Makefile's stage-cmd-rs — no dedicated target here.
# (apps/palmer/build.py still works for building palmer standalone during dev.)

# Full Debian userland: docker export gives us a tarball of the entire image
# filesystem, which includes Mesa drivers, GTK/Qt libs, foot terminal,
# Xwayland, dbus-daemon, seatd, etc. — everything a real userland needs.
# We exclude /cjyx (we ship our own builds via dedicated targets) and the
# kernel-mounted virtual filesystems (/proc /sys /dev mountpoints get
# created fresh in the rootfs and mounted at runtime).
#
# This export (docker export | tar -x of the whole fs) plus the disk
# Makefile's `cp -a` of it is multi-minute work, and it used to run on EVERY
# `make run-g` because it depended on the phony `build-image` (always "newer").
# But the rootfs contents are determined solely by the Dockerfile's package
# set — our own binaries are pruned out (`rm -rf .../cjyx`), so a zonule/C
# source change doesn't alter the base at all. So we now key the re-export on
# the Dockerfile (a real file): it only re-runs when you actually change what's
# installed. `build-image` stays as an order-only prereq — it still runs (cheap
# when the docker layer cache is warm) to guarantee the image exists before we
# export, but per Make's order-only rule it no longer forces a re-export.
$(BUILD)/.debian_rootfs: $(USERLAND)/Dockerfile | build-image $(BUILD)
	rm -rf $(BUILD)/debian-rootfs
	mkdir -p $(BUILD)/debian-rootfs
	# Extract the WHOLE container filesystem, THEN prune. Excluding paths during
	# `tar -x` of a `docker export` stream is fragile: docker emits hardlinks,
	# and if an --exclude pattern drops the member that carries a hardlink's
	# data, GNU tar aborts with "Cannot stat" (nondeterministic, by member
	# order) and leaves a half-written, self-inconsistent merged-/usr tree —
	# which then makes the disk Makefile's `cp -a` fail with "File exists".
	# Extracting everything keeps every hardlink target present; we delete what
	# we don't want afterwards. `set -o pipefail` so a real export/tar failure
	# is not masked by the trailing `docker rm`.
	set -o pipefail; \
	  cid=$$(docker create --platform $(PLATFORM) $(DOCKER_IMAGE)); \
	  docker export $$cid | tar -x -C $(BUILD)/debian-rootfs; \
	  status=$$?; \
	  docker rm $$cid >/dev/null; \
	  exit $$status
	rm -rf $(BUILD)/debian-rootfs/cjyx \
	       $(BUILD)/debian-rootfs/.dockerenv \
	       $(BUILD)/debian-rootfs/proc/* \
	       $(BUILD)/debian-rootfs/sys/* \
	       $(BUILD)/debian-rootfs/dev/*
	touch $@

cmd: build-image | $(BUILD)
	rm -rf $(BUILD)/cmd
	cid=$$(docker create --platform $(PLATFORM) $(DOCKER_IMAGE)); \
	  docker cp $$cid:/cjyx/cmd/bin $(BUILD)/cmd; \
	  docker rm $$cid >/dev/null

# Rust workspace of coreutil-style commands. Same Rust-in-docker pattern as
# squishy/dinky but produces N binaries (one per workspace member crate)
# into build/cmd-rs/. The disk Makefile's stage-cmd-rs target installs each
# one into rootfs/bin alongside the C commands from build/cmd/.
cmd-rs: $(CMDRS_SRC)/build-rust.py $(CMDRS_SRC)/Dockerfile.rust $(WORKSPACE) $(wildcard $(CMDRS_SRC)/*/Cargo.toml) $(wildcard $(CMDRS_SRC)/*/src/*.rs) | $(BUILD)
	rm -rf $(BUILD)/cmd-rs
	mkdir -p $(BUILD)/cmd-rs
	python3 $(CMDRS_SRC)/build-rust.py $(BUILD)/cmd-rs

image: $(BUILD)/init $(BUILD)/cjsh $(BUILD)/display $(BUILD)/squishy $(BUILD)/dinky cmd cmd-rs $(BUILD)/.debian_rootfs $(DATA)
	$(MAKE) -C $(DISK) image

# Flashable Raspberry Pi 4 SD-card image: a FAT32 boot partition (firmware +
# config.txt + kernel Image + dtb) followed by the ext4 root partition. Depends
# on the same rootfs staging as `image`, plus the kernel and firmware blobs.
sd-card: $(SDIMG)
$(SDIMG): $(BUILD)/init $(BUILD)/cjsh $(BUILD)/display $(BUILD)/squishy $(BUILD)/dinky cmd cmd-rs $(BUILD)/.debian_rootfs $(KERNEL)
	$(MAKE) -C $(DISK) rootfs
	KERNEL_IMAGE="$(KERNEL)" DTB="$(DTB)" RPIBOOT="$(RPIBOOT)" \
	  ROOTFS="$(DISK)/rootfs" OUT="$(SDIMG)" $(DISK)/mksd.sh

run: image
	$(QEMU_HEADLESS) -append "$(ROOT_CMDLINE) init=/init"
run-shell-only: image
	$(QEMU_HEADLESS) -append "$(ROOT_CMDLINE) init=/bin/cjsh"
run-graphical: image
	$(QEMU_GRAPHICAL) -append "$(ROOT_CMDLINE) init=/init"
run-graphical-shell-only: image
	$(QEMU_GRAPHICAL) -append "$(ROOT_CMDLINE) init=/bin/cjsh"

run-g:  run-graphical
run-gs: run-graphical-shell-only

# Fast-iteration variants: same as run-g/run-gs but zonule builds with the
# no-LTO dev profile, so the compositor recompiles in a fraction of the time.
run-g-dev:
	$(MAKE) run-graphical ZONULE_DEV=1
run-gs-dev:
	$(MAKE) run-graphical-shell-only ZONULE_DEV=1

clean:
	$(MAKE) -C $(USERLAND) clean
	$(MAKE) -C $(DISK) clean
	rm -rf $(BUILD)/init $(BUILD)/cjsh $(BUILD)/display $(BUILD)/squishy $(BUILD)/dinky $(BUILD)/palmer $(BUILD)/palmer-target $(BUILD)/cmd $(BUILD)/cmd-rs $(BUILD)/cmd-rs-target $(BUILD)/disk.img $(BUILD)/sdcard.img

# Reset /home only (leaves the built system alone). Next `make run` recreates
# an empty data.img.
clean-data:
	rm -f $(DATA)

clean-all: clean clean-data
	rm -rf $(BUILD)
