//! Shared render helpers for both backends (tty + winit).
//!
//! Both backends draw the same scene: the window `Space` plus a set of "custom"
//! elements layered *on top* of it. Two kinds of custom element live here:
//!   - the mouse cursor (an xcursor image uploaded as a texture), and
//!   - thin window borders (solid-colour rectangles framing each window).
//!
//! `render_output` takes a single custom-element type `E`, so to mix the two we
//! wrap them in the `ZonuleElement` enum generated by Smithay's `render_elements!`
//! macro. Both backends use `GlesRenderer`, so the enum is fixed to it (no
//! generics) — this is the small bit of plumbing anvil buries inside its SSD
//! machinery.

use std::time::Duration;

use smithay::{
    backend::{
        allocator::Fourcc,
        renderer::{
            element::{
                Kind,
                memory::{MemoryRenderBuffer, MemoryRenderBufferRenderElement},
                solid::{SolidColorBuffer, SolidColorRenderElement},
            },
            gles::GlesRenderer,
        },
    },
    desktop::{Space, Window},
    utils::{Logical, Point, Transform},
};

use crate::cursor::Cursor;

// --- Tunables -------------------------------------------------------------
//
// GAP is the margin `arrange` leaves around and between windows (the gutters
// the background shows through). BORDER is the border thickness; keep it < GAP
// so a window's border sits inside its gutter without touching its neighbour's.
/// Margin around/between tiled windows, in logical px. Used by `Zonule::arrange`.
pub const GAP: i32 = 8;
/// Window border thickness, in logical px.
pub const BORDER: i32 = 2;
/// Border colour for the focused window (RGBA, 0..1).
const FOCUS_COLOR: [f32; 4] = [0.35, 0.60, 0.85, 1.0];
/// Border colour for unfocused windows (RGBA, 0..1).
const BORDER_COLOR: [f32; 4] = [0.25, 0.25, 0.28, 1.0];

// One element type for `render_output`, unifying the cursor and the borders.
smithay::backend::renderer::element::render_elements! {
    pub ZonuleElement<=GlesRenderer>;
    Cursor = MemoryRenderBufferRenderElement<GlesRenderer>,
    Solid = SolidColorRenderElement,
}

/// Build all custom elements (cursor + window borders) for one frame, front to
/// back. The cursor is pushed first so it draws on top of the borders; both are
/// custom elements, so they draw on top of the window `Space`.
pub fn scene_elements(
    renderer: &mut GlesRenderer,
    space: &Space<Window>,
    focused: Option<&Window>,
    cursor: &Cursor,
    pointer_location: Point<f64, Logical>,
    time: Duration,
) -> Vec<ZonuleElement> {
    let mut elements = Vec::new();
    if let Some(cursor) = cursor_element(renderer, cursor, pointer_location, time) {
        elements.push(cursor);
    }
    elements.extend(border_elements(space, focused));
    elements
}

/// A thin border framing each window: four solid rectangles sitting just outside
/// the window rect (in the gutter left by `GAP`). The focused window gets a
/// different colour so you can tell which is active.
fn border_elements(space: &Space<Window>, focused: Option<&Window>) -> Vec<ZonuleElement> {
    let b = BORDER;
    let mut out = Vec::new();
    for window in space.elements() {
        let Some(geo) = space.element_geometry(window) else {
            continue;
        };
        let (x, y, w, h) = (geo.loc.x, geo.loc.y, geo.size.w, geo.size.h);
        let color = if Some(window) == focused {
            FOCUS_COLOR
        } else {
            BORDER_COLOR
        };
        out.push(solid(x - b, y - b, w + 2 * b, b, color)); // top
        out.push(solid(x - b, y + h, w + 2 * b, b, color)); // bottom
        out.push(solid(x - b, y, b, h, color)); // left
        out.push(solid(x + w, y, b, h, color)); // right
    }
    out
}

/// One solid-colour rectangle as a `ZonuleElement`. Coordinates are logical;
/// with scale 1 they map straight to physical.
fn solid(x: i32, y: i32, w: i32, h: i32, color: [f32; 4]) -> ZonuleElement {
    let buffer = SolidColorBuffer::new((w, h), color);
    SolidColorRenderElement::from_buffer(&buffer, (x, y), 1.0, 1.0, Kind::Unspecified).into()
}

/// The default-theme cursor at `pointer_location`, or `None` if it can't be
/// built. Always draws the theme arrow; honoring client-set cursors / hiding is
/// a later refinement.
fn cursor_element(
    renderer: &mut GlesRenderer,
    cursor: &Cursor,
    pointer_location: Point<f64, Logical>,
    time: Duration,
) -> Option<ZonuleElement> {
    let image = cursor.get_image(1, time);

    let buffer = MemoryRenderBuffer::from_slice(
        &image.pixels_rgba,
        Fourcc::Argb8888,
        (image.width as i32, image.height as i32),
        1,
        Transform::Normal,
        None,
    );

    // Put the cursor's hotspot at the pointer, then convert to physical space
    // (scale 1 until we do HiDPI).
    let location = (pointer_location
        - Point::<f64, Logical>::from((image.xhot as f64, image.yhot as f64)))
    .to_physical(1.0);

    match MemoryRenderBufferRenderElement::from_buffer(
        renderer,
        location,
        &buffer,
        None,
        None,
        None,
        Kind::Cursor,
    ) {
        Ok(element) => Some(element.into()),
        Err(err) => {
            tracing::warn!("failed to build cursor element: {err:?}");
            None
        }
    }
}
